language: node_js
node_js:
  - "node"
  - "lts/*"

install: true

cache:
  yarn: true
  directories: node_modules

before_script: yarn install && yarn typed
script: yarn test
after_success: yarn run coverage
